repos:
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args:
          [
            "--indent-size",
            "4",
            "--force-function-style",
            "fnpar",
            "obsidian.sh",
          ]
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
