repos:
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args:
          [
            "--indent-size",
            "2",
            "--force-function-style",
            "fnpar",
            "--tab",
            "obsidian.sh",
          ]
