repos:
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args:
          [
            "--indent-size",
            "2",
            "--force-function-style",
            "fnpar",
            "--tab",
            "obsidian.sh",
          ]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: shellcheck
