repos:
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args:
          [
            "--indent-size",
            "4",
            "--force-function-style",
            "fnpar",
            "obsidian.sh",
          ]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    - id: shellcheck
      args: ["--severity=warning"]  # Optionally only show errors and warnings

default_language_version:
    python: python3.10